name: Bug report
description: Report a bug. For security vulnerabilities see Report a security vulnerability in the templates.
title: "BUG: <Please write a comprehensive title after the 'BUG: ' prefix>"
labels: [00 - Bug]

body:    
- type: textarea
  attributes: 
    label: "Describe the issue:"
  validations:
    required: true

- type: textarea
  attributes:
    label: "Reproduce the code example:"
    description: >
      A short code example that reproduces the problem. 
    placeholder: |
      << your code here >>
  validations:
    required: true
  
- type: textarea
  attributes:
    label: "Error message:"
    description: >
      Please include full error message, if any. text or screenshots